
[micronaut]
application.name = 'authentication'
security.authentication = 'cookie'

[datasources.default]
driver-class-name = 'org.postgresql.Driver'
db-type = 'postgres'

[micronaut.router.static-resources.jsonschema]
paths = 'classpath:META-INF/schemas'
mapping = '/schemas/**'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.rapidoc]
paths = 'classpath:META-INF/swagger/views/rapidoc'
mapping = '/rapidoc/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'
