micronaut:
  application:
    name: register
    static-resources:
      jsonschema:
        paths: classpath:META-INF/schemas
        mapping: /schemas/**
  security:
    hash-configuration:
      type: ARGON2id     
      iterations: 3      
      memory: 65536      
      parallelism: 4
      hash-length: 64    
      salt-length: 16    
  server:
    port: 8080



datasources:
  default:
    url: jdbc:mysql://localhost:3306/register?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 600000
    max-lifetime: 1800000

logger:
  levels:
    io.micronaut.email: TRACE